# Generated by Django 3.1.1 on 2020-09-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('discount', models.FloatField()),
                ('type_of_discount', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('valid', models.DateTimeField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
    ]
