# Generated by Django 3.1 on 2020-09-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='meta_desc',
            field=models.CharField(default='default', max_length=144),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='meta_url',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
