# Generated by Django 3.1 on 2020-09-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='meta',
        ),
        migrations.AddField(
            model_name='product',
            name='meta_url',
            field=models.CharField(default=' ', max_length=100, unique=True),
        ),
    ]
