# Generated by Django 3.1.1 on 2020-09-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200911_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
